#!/bin/sh

# This will turn your input into md5 hash.
# If no input is given it will provide the previous hashed input

var="$1"
echo -n "${var}: \n" >> ~/Desktop/hashed.log | md5sum | cut -d " " -f 1 | xargs echo >> ~/Desktop/hashed.log
